//always two params, state is not application state, 
//only the state this reducer is responsible for ; value responsible for books
//state that was previoulsy generated by this reducer
export default function(state = null, action) {
	switch(action.type) {
		case 'BOOK_SELECTED':
			//return fresh object
			return action.payload;
	}
	//reducer will be called whenever an action is dispatched 
	/*
		states and props are related !
		The state of one component 
		will often become the props of a child component.
	*/
	return state; 
}